# DATASET FROM CHEMBL

## Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [5]:
data = pd.read_csv('dataset.csv')
display(data)

,molecule_id,pXC50,b0001,b0002,b0003,b0004,b0005,b0006,b0007,b0008,...,b1015,b1016,b1017,b1018,b1019,b1020,b1021,b1022,b1023,b1024
0,CHEMBL10016,7.301,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
1,CHEMBL10019,6.071,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
2,CHEMBL10092,5.357,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
3,CHEMBL100954,7.260,1,1,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL101069,7.616,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,CHEMBL96723,7.480,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1167,CHEMBL96746,7.572,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1168,CHEMBL96831,5.439,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1169,CHEMBL96906,6.325,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1170,CHEMBL96932,7.167,1,1,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,0

In [22]:
train, test = train_test_split(data, random_state=1)
known, unknown = train_test_split(train, test_size=0.1, random_state=1)

X_known = known.drop(["molecule_id", "pXC50"], axis=1)
X_unknown = unknown.drop(["molecule_id", "pXC50"], axis=1)
X_test = test.drop(["molecule_id", "pXC50"], axis=1)

y_known = known["pXC50"]
y_unknown = unknown["pXC50"]
y_test = test["pXC50"]

In [ ]:
pipelines = [
    Pipeline
]